service: todo-service

package:
  individually: true

frameworkVersion: '=2.43.0'
variablesResolutionMode: 20210326
configValidationMode: error

provider:
  lambdaHashingVersion: 20201221
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, "local"}
  region: ${opt:region, "us-east-1"}
  iam: ${file(./serverless.iam.yml)}
    
custom:
  serverless-offline-ssm:
    stages:
      - local
    ssm: ${file(./serverless.ssm.yml):ssmVarsOffline}
  serverless-offline:
    noPrependStageInUrl: true
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
    packager: 'yarn' # Packager that will be used to package your external modules
  warmup:
    enabled: true
    events:
      - schedule: rate(5 minutes)
    prewarm: true
    concurrency: 1
  prune:
    automatic: true
    number: 5 # Number of versions to keep
  ssmVars: ${file(./serverless.ssm.yml):ssmVars}

functions:
  - ${file(./src/handlers/todos/serverless.yml)}

plugins:
  - serverless-webpack
  - serverless-offline-ssm
  - serverless-offline
  - serverless-prune-plugin
