service: todo-service

package:
  individually: true

frameworkVersion: '=2.43.0'

provider:
  lambdaHashingVersion: 20201221
  name: aws
  runtime: nodejs14.x

  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 'lambda:InvokeFunction'
          Resource: '*'

custom:
  serverless-offline:
    noPrependStageInUrl: true
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
    packager: 'yarn' # Packager that will be used to package your external modules
  warmup:
    enabled: true
    events:
      - schedule: rate(5 minutes)
    prewarm: true
    concurrency: 1
  prune:
    automatic: true
    number: 5 # Number of versions to keep

functions:
  emailGetEmailContent:
    handler: src/handlers/todos/get-todos.main
    events:
      - http:
          path: /todos
          method: get

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-prune-plugin
